### ISSUE TITLE
could not link with cufft 

### ISSUE THREAD

**Issue by shanyangmeh** [gy20073/compact_bilinear_pooling#1]
append CUDA_cufft_LIBRARY to Caffe_LINKER_LIBS in Cuda.cmake file

**Comment by gy20073** [comment]
Thanks! I believe it should be "CUDA_CUFFT_LIBRARIES", see docs at this page:
https://cmake.org/cmake/help/v3.0/module/FindCUDA.html

I've updated the Cuda.cmake file.

Please let me know if you have any further problems with cmake, as I usually use Makefile.config to compile.
