### ISSUE TITLE
Error in Training 

### ISSUE THREAD

**Issue by sandareka** [gy20073/compact_bilinear_pooling#13]
Hi, 

Thanks for releasing your code. 
I want to use your compact bilinear feature to do birds classification as described in examples/compact_bilinear

I hope to use CompactBilinear layers with my exisitng Caffe version, so as described in the readme I added all the layer files to respective folders of my Caffe installation. Caffe was built successfully. Then I tried to train VGG with bilinear layers as given in examples/compact_bilieaner. However, I'm getting following error. 

`I0913 13:31:49.494161  5988 solver.cpp:87] Creating training net from net file: examples/compact_bilinear/ft_all.prototxt
[libprotobuf ERROR C:\Users\guillaume\work\caffe-builder\build_v140_x64\packages\protobuf\protobuf_download-prefix\src\protobuf_download\src\google\protobuf\text_format.cc:298] Error parsing text-format caffe.NetParameter: 425:26: Message type "caffe.LayerParameter" has no field named "compact_bilinear_param".
F0913 13:31:49.494161  5988 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: examples/compact_bilinear/ft_all.prototxt
*** Check failure stack trace: ***`

Where am I doing wrong? Do I have to change layer_factory file as well? Really appreciate if you can help me. 

Thank you in advance!

**Comment by gy20073** [comment]
Have you add this to proto file?

src/caffe/proto/caffe.proto
  add "optional CompactBilinearParameter compact_bilinear_param=145;" in the "message LayerParameter". 

and change 145 to the most recent available slot? it seems right now should be 147

**Comment by sandareka** [comment]
@gy20073 Thank you! I resolved the problem. May I please know if the models [here ](https://drive.google.com/drive/folders/0B0ldy05JZFSaS1pIUjBaSUxMTUU) are already trained models  and ready to use models for bird classification?

Thank you in advance!

**Comment by gy20073** [comment]
@sandareka yes they are already pertained for bird classification

**Comment by sandareka** [comment]
Hi @gy20073 , 

Thank you for your prompt reply. However, unfortunately almost all the classifications are wrong when I use those models. Here is my code. Could you please be kind enough to point out my error? 

`#load the model
    net = caffe.Net('models_/new_ft_all.prototxt',
                    'models_/new_ft_all_iter_20000.caffemodel',
                    caffe.TEST)
    # load input and configure preprocessing
    transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
    transformer.set_transpose('data', (2,0,1))
    transformer.set_channel_swap('data', (2,1,0))
    transformer.set_raw_scale('data', 255.0)
    net.blobs['data'].reshape(1,3,512,512)

    folder_name = "D:/Data/birds datasets/CUB_200_2011/images/001.Black_footed_Albatross"
    # load the image in the data layer
    for filename in os.listdir(folder_name):
        image_path = os.path.join(folder_name, filename)
        pre_processed_image = caffe.io.load_image(image_path)
        net.blobs['data'].data[...] = transformer.preprocess('data', pre_processed_image)
        out = net.forward()
        predicted_class = out['fc8_cub'].argmax()
        print(predicted_class)`

Anyway as point out by another user I will try to use your model with cuda 7 or I will try with your version of caffe.

**Comment by sandareka** [comment]
@gy20073 When I used your pretrained model with cuda 8 and cudnn 5.1 it is working fine. 
Thank you very much for your coporation

**Comment by MohamedElrefai** [comment]
@gy20073  @sandareka  I have changed it to 147 but still having the same error ?
[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 382:26: Message type "caffe.LayerParameter" has no field named "compact_bilinear_param"

**Comment by pangjh3** [comment]
@gy20073 @sandareka   I have changed it to 147 but still having the same error ?
I use pycaffe, and successfully make pycaffe. Then I import this caffe branch. But still did not work.
How can I do?
