### ISSUE TITLE
caffe version compact bilinear can not converge

### ISSUE THREAD

**Issue by trantorznh** [gy20073/compact_bilinear_pooling#2]
I fine-tuning on the cifar10 example, but it almost can not converge or converge quite slowly. Would you give some examples for using the compace bilinear layer. Thank you

**Comment by gy20073** [comment]
sure, I will push an running example in a while.

**Comment by cvwer** [comment]
where is the example network on CUB dataset?

**Comment by gy20073** [comment]
Hi all, I uploaded an example on CUB. It's in $CAFFE_ROOT/examples/compact_bilinear
