### ISSUE TITLE
Bird classification example loss does not converge

### ISSUE THREAD

**Issue by zongyuange** [gy20073/compact_bilinear_pooling#3]
Hi, Thanks for your code. I followed your instructions to test run the fy_last_layer.sh provided in the example for bird classification. However, the performance does not quite make sense (keeps showing close to 0 mean accuracy). 

I guess the main problem might be the VGG model I downloaded was trained with 224 by 224 input while your ft_last_layer.pt is 512 by 512. I have one following question:
Does image input size 512 vs 224 affect the performance by a huge margin?

Many thanks!

**Comment by gy20073** [comment]
Hi Zongyuan,

I've confirmed that it works on my side. Can you make a git pull and make clean, make all to ensure that you're using the right version?

Let me know if it still doesn't work

Thanks

**Comment by zongyuange** [comment]
Thanks, I will do it again and let you know the results.

**Comment by zongyuange** [comment]
Hi Yao,
This problem has been solved once I compiled the code with CUDA 8.0.
Thanks
