### ISSUE TITLE
Error on signed_sqrt_layer

### ISSUE THREAD

**Issue by Ellyuca** [gy20073/compact_bilinear_pooling#30]
Hi.
I am trying to use this version of caffe. I have followed the instructions from BVLC caffe version for the installation.
I am getting this error when I use the command make all:

![error_cbp](https://user-images.githubusercontent.com/9151725/173105544-229cc44d-c9ef-4a99-ab7f-18ee575215ae.png)

I am using python 3.6.9 and I tried to install this version of caffe for cpu.

Any ideas on how to fix this?

Thanks!

**Comment by gy20073** [comment]
maybe you can try to remove the static or const modifier? I am not quite sure, it might be related to some c++ initialization grammar.

**Comment by Ellyuca** [comment]
Hi @gy20073,
I removed the "static" and I was able to compile it.

Thank you for the help!!
Best regards.
