### ISSUE TITLE
Cudnn v5 is not supported

### ISSUE THREAD

**Issue by guopei** [gy20073/compact_bilinear_pooling#4]
I tried making with cudnn v5 but got the following error "error: too few arguments to function ‘cudnnStatus_t cudnnSetPooling2dDescriptor"

[This page](https://github.com/BVLC/caffe/issues/3969) tells me cudnn v5 is not supported. Switching to cudnn v4 solves the problem.

It will be better if we add a note in the readme page...

**Comment by gy20073** [comment]
Thanks for pointing this out! I've added a note in readme

**Comment by zimenglan-sysu-512** [comment]
hi @gy20073, when will you release v5 code? thanks.

**Comment by gy20073** [comment]
@zimenglan-sysu-512 I don't have a plan for releasing v5 code now... You could merge the changed files manually. The changed files are documented at the readme in Caffe folder.
