### ISSUE TITLE
在ubuntu16.04环境下编译不成功

### ISSUE THREAD

**Issue by dailai** [gy20073/compact_bilinear_pooling#8]
敬爱的作者，您好，首先很感谢您做出的贡献。但是我在ubuntu16.04的环境下编译通不过，请问您能写一个在ubuntu16.04环境下编译通过的不。

**Comment by dailai** [comment]
就是make runtest的时候总是报错

**Comment by gy20073** [comment]
Make runtest不通过也可以用的

Yang Gao

**Comment by dailai** [comment]
make runtest 不通过，然后使用的时候和makeruntest 报同样的错误Aborted at 1490246863 (unix time) try "date -d @1490246863" if you are using GNU date ***，经过测试发现是compact_bilinear的代码有问题，如果移除这个，make runtest会通过

**Comment by gy20073** [comment]
能贴出来具体的make runtest 的error吗？

**Comment by dailai** [comment]
LayerFactoryTest/2.TestCreateLayer
*** Error in `.build_release/test/test_all.testbin': double free or corruption (out): 0x000000001aa9f7a0 ***
*** Aborted at 1490246863 (unix time) try "date -d @1490246863" if you are using GNU date ***
PC: @     0x7faa6378a267 (unknown)
*** SIGABRT (@0x3e800003a01) received by PID 14849 (TID 0x7faa6a92da00) from PID 14849; stack trace: ***
    @     0x7faa63b2fd10 (unknown)
    @     0x7faa6378a267 (unknown)
    @     0x7faa6378beca (unknown)
    @     0x7faa637cdc53 (unknown)
    @     0x7faa637d5c69 (unknown)
    @     0x7faa637d989c (unknown)
    @     0x7faa6442137f caffe::CompactBilinearLayer<>::~CompactBilinearLayer()
    @     0x7faa644217c9 caffe::CompactBilinearLayer<>::~CompactBilinearLayer()
    @           0x91103b caffe::LayerFactoryTest_TestCreateLayer_Test<>::TestBody()
    @           0x95b723 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9538ba testing::Test::Run()
    @           0x953a08 testing::TestInfo::Run()
    @           0x953ae5 testing::TestCase::Run()
    @           0x954478 testing::internal::UnitTestImpl::RunAllTests()
    @           0x954743 testing::UnitTest::Run()
    @           0x4727cf main
    @     0x7faa63775a40 (unknown)
    @           0x47a5e9 _start
    @                0x0 (unknown)
Makefile:532: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

**Comment by gy20073** [comment]
不好意思我当前没办法直接看出来是为什么failed。

我会在我有时间的时候去debug一下！最近一周暂时没有时间来看

**Comment by guopei** [comment]
@dailai 

我在Ubuntu 16.04编译是没问题的，也能正常使用。

**Comment by guopei** [comment]
@dailai 

你贴的信息是make runtest的输出吧，能不能贴使用prototxt的时候出的错？

**Comment by dailai** [comment]
谢谢您，问题我已经解决了！没问题了。

**Comment by sunjian2015** [comment]
@dailai 请问您是怎么解决的啊？那个compact_bilinear代码哪里有问题呢？我也遇到了同样的问题。谢谢啦

**Comment by kli017** [comment]
@dailai 你好 我也遇到runtest编译报相同的错误，请问你问题怎么解决的？
